<?php


namespace shop\forms;


use kartik\base\Config;
use shop\entities\User;
use yii\base\Model;

class UserEditForm extends Model
{
    public $username;
    public $email;
    public $password;
    public $status;
    public $_user;

    public function __construct(User $user, $config = [])
    {
        $this->username = $user->username;
        $this->email = $user->email;
        //$this->password = $user->password;
        //   if(!empty($user->password))

        $this->_user = $user;

        parent::__construct($config);
    }

    public function rules(): array
    {
        return [
            [['username','email'], 'required' ],
            ['email','email'],
            [['email'], 'string', 'max'=> 255],
            [['username','email'], 'unique', 'targetClass' => User::class, 'filter' => ['<>', 'id', $this->_user->id] ],
            ['password', 'string', 'min'=>4 ],

        ];
        //return parent::rules(); // TODO: Change the autogenerated stub
    }
}