<?php


namespace shop\forms;

use shop\entities\User;
use yii\base\Model;

class UserCreateForm extends Model
{
    public $username;
    public $email;
    public $password;
    public $status;
    //public $auth_key;

    public function rules(): array
    {
        return [
            [['username','email'], 'required' ],
            ['email','email'],
            [['username','email'], 'string', 'max'=> 255],
            [['username','email'], 'unique', 'targetClass' => User::class ],
            ['password', 'string', 'min'=>4 ],

        ];
        //return parent::rules(); // TODO: Change the autogenerated stub
    }

}