<?php


namespace shop\entities\Shop;

use yii\db\ActiveRecord;

/*
 * @property integer $id
 * @property integer $name
 * @property integer $slug
 * */

class Tag extends ActiveRecord
{
    public static function create($name, $slug): self
    {
        $tag  =  new static();
        $tag->name = $name;
        $tag->slug = $name;
        return $tag;
    }

    public function edit($name, $slug): viod
    {
        $this->name = $name;
        $this->slug = $name;
    }

    public static function tableName()
    {
       return '{{%shop_tags}}';
      //  return parent::tableName(); // TODO: Change the autogenerated stub
    }

    public function delelte()
    {

    }

}