<?php
namespace shop\entities\behaviors;

//use Codeception\Step\Meta;
use shop\entities\Meta;
use yii\base\Behavior;
use yii\base\Event;
use yii\db\ActiveRecord;
use yii\helpers\Json;

class MetaBehavior extends Behavior
{

    public $attribute = 'meta';
    public $jsonAttribute = 'meta_json';

    public function events():array
    {
        return [
            ActiveRecord::EVENT_AFTER_FIND => 'onAfterFind',
            // для onBeforeSave
            ActiveRecord::EVENT_BEFORE_INSERT => 'onBeforeSave',
            ActiveRecord::EVENT_BEFORE_UPDATE => 'onBeforeSave',

        ];
    }


//    public function attach($owner)
//    {
//        $brand = $owner;
//        //$brand->on(ActiveRecord::EVENT_AFTER_FIND, function (Event $event){
//        $brand->on(ActiveRecord::EVENT_AFTER_FIND, [$this, 'onAfterFind']);
//        parent::attach($owner); // TODO: Change the autogenerated stub
//    }


    public function onAfterFind(Event $event): void
    {
        $brand = $event->sender;
        $meta = Json::decode($brand->getAttribute('meta_json'));
        $brand->meta = new Meta($meta['title'], $meta['description'], $meta['keywords']);
    }

    public function onBeforeSave(Event $event): void
    {
        $model = $event->sender;
        $model->setAttribute('meta_json', Json::encode([
            'title' => $model->{$this->attribute}->title,
            'description' => $model->{$this->attribute}->description,
            'keywords' => $model->{$this->attribute}->keywords,
        ]));
    }

}