<?php


namespace shop\entities\behaviors;


//use Codeception\Step\Meta;
use shop\entities\Meta;
use yii\base\Behavior;
use yii\base\Event;
use yii\db\ActiveRecord;
use yii\helpers\Json;

class MetaBehavior extends Behavior
{
    public function events():array
    {
        return [
            ActiveRecord::EVENT_AFTER_FIND => 'onAfterFind',
            /* для onBeforeSave
            ActiveRecord::EVENT_BEFORE_INSERT => 'onBeforeSave',
            ActiveRecord::EVENT_BEFORE_UPDATE => 'onBeforeSave',
            */
        ];
    }


//    public function attach($owner)
//    {
//        $brand = $owner;
//        //$brand->on(ActiveRecord::EVENT_AFTER_FIND, function (Event $event){
//        $brand->on(ActiveRecord::EVENT_AFTER_FIND, [$this, 'onAfterFind']);
//        parent::attach($owner); // TODO: Change the autogenerated stub
//    }

    public function onAfterFind(Event $event): viod
    {
        $brand = $event->sender;

        $meta = Json::decode($brand->getAttribute('meta_json'));
        $brand->meta = new Meta($meta['title'], $meta['description'], $meta['keywords']);
    }

    // TODO Можно перенести так же onBeforeSave

}